import { readFile } from 'node:fs/promises';

export const DISTRIBUTION_MARK = 'autotool';
export const DISTRIBUTION_MARK_OLD = 'autogenerated';

/**
 * Checks if a file is managed by autotool. It is managed if the file bears a
 * mark saying 'autotool'
 */
export const isManagedFile = async (path: string): Promise<boolean> => {
	try {
		const content = await readFile(path, { encoding: 'utf8' });
		return content.includes(DISTRIBUTION_MARK) || content.includes(DISTRIBUTION_MARK_OLD);
	} catch {
		return false;
	}
};
