import { readFile } from 'node:fs/promises';

export const AUTOTOOL_MARK = 'managed-by-autotool';
export const OLD_MARK = 'autogenerated';

export const isManagedFile = async (path: string, mark = AUTOTOOL_MARK): Promise<boolean> => {
	try {
		const content = await readFile(path, { encoding: 'utf8' });
		return content.includes(mark) || content.includes(OLD_MARK);
	} catch (error) {
		// The file not exists error is the only one we treat as valid
		return (error as NodeJS.ErrnoException).code === 'ENOENT';
	}
};
